// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    #[prost(oneof = "message::Msg", tags = "1, 2, 3")]
    pub msg: ::core::option::Option<message::Msg>,
}
/// Nested message and enum types in `Message`.
pub mod message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Msg {
        #[prost(message, tag = "1")]
        Generic(super::generic::Message),
        #[prost(message, tag = "2")]
        Discovery(super::discovery::Message),
        #[prost(message, tag = "3")]
        Ble(super::ble::Message),
    }
}
