// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetBdAddressCmd {
    #[prost(bytes = "vec", tag = "1")]
    pub bd_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "BleAddrType", tag = "2")]
    pub addr_type: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SniffAdvCmd {
    /// Extended advertisements (BLE 5).
    #[prost(bool, tag = "1")]
    pub use_extended_adv: bool,
    /// Channel can be specified, the device will only
    /// listen on this specific channel.
    #[prost(uint32, tag = "2")]
    pub channel: u32,
    #[prost(bytes = "vec", tag = "3")]
    pub bd_address: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct JamAdvCmd {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct JamAdvOnChannelCmd {
    #[prost(uint32, tag = "1")]
    pub channel: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SniffConnReqCmd {
    #[prost(bool, tag = "1")]
    pub show_empty_packets: bool,
    #[prost(bool, tag = "2")]
    pub show_advertisements: bool,
    #[prost(uint32, tag = "3")]
    pub channel: u32,
    #[prost(bytes = "vec", tag = "4")]
    pub bd_address: ::prost::alloc::vec::Vec<u8>,
}
/// *
/// SniffAccessAddressCmd
///
/// Sniff Access Addresses sent over BLE.
///
/// Will send AccessAddressDiscovered notifications each
/// time an AccessAddress has been found.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SniffAccessAddressCmd {
    #[prost(bytes = "vec", tag = "6")]
    pub monitored_channels: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SniffActiveConnCmd {
    #[prost(uint32, tag = "1")]
    pub access_address: u32,
    #[prost(uint32, tag = "2")]
    pub crc_init: u32,
    #[prost(bytes = "vec", tag = "3")]
    pub channel_map: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "4")]
    pub hop_interval: u32,
    #[prost(uint32, tag = "5")]
    pub hop_increment: u32,
    #[prost(bytes = "vec", tag = "6")]
    pub monitored_channels: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct JamConnCmd {
    #[prost(uint32, tag = "1")]
    pub access_address: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ScanModeCmd {
    #[prost(bool, tag = "1")]
    pub active_scan: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AdvModeCmd {
    #[prost(bytes = "vec", tag = "1")]
    pub scan_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub scanrsp_data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetAdvDataCmd {
    #[prost(bytes = "vec", tag = "1")]
    pub scan_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub scanrsp_data: ::prost::alloc::vec::Vec<u8>,
}
/// *
/// CentralModeCmd
///
/// Enable central mode.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CentralModeCmd {}
/// *
/// ConnectToCmd
///
/// Connect to a specific target device.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConnectToCmd {
    #[prost(bytes = "vec", tag = "1")]
    pub bd_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "BleAddrType", tag = "2")]
    pub addr_type: i32,
    #[prost(uint32, optional, tag = "3")]
    pub access_address: ::core::option::Option<u32>,
    #[prost(bytes = "vec", optional, tag = "4")]
    pub channel_map: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(uint32, optional, tag = "5")]
    pub hop_interval: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "6")]
    pub hop_increment: ::core::option::Option<u32>,
    #[prost(uint32, optional, tag = "7")]
    pub crc_init: ::core::option::Option<u32>,
}
/// *
/// SendRawPDUCmd
///
/// Sends a raw PDU (to peripheral if in central mode, to central
/// if in peripheral mode).
///
/// If device is able to send raw packets, `access_address` and
/// `crc` can be provided.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendRawPduCmd {
    #[prost(enumeration = "BleDirection", tag = "1")]
    pub direction: i32,
    #[prost(uint32, tag = "2")]
    pub conn_handle: u32,
    #[prost(uint32, tag = "3")]
    pub access_address: u32,
    #[prost(bytes = "vec", tag = "4")]
    pub pdu: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "5")]
    pub crc: u32,
    #[prost(bool, tag = "6")]
    pub encrypt: bool,
}
/// *
/// SendPDUCmd
///
/// Sends a raw PDU
/// If no direction is provided, the following rules are applied:
/// - send to peripheral if in central mode
/// - send to central if in peripheral mode
/// - inject into the synchronized connection if in sniffer mode
/// If a direction is provided, use the direction.
///
/// If device is able to send raw packets, `access_address` and
/// `crc` can be provided.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendPduCmd {
    #[prost(enumeration = "BleDirection", tag = "1")]
    pub direction: i32,
    #[prost(uint32, tag = "2")]
    pub conn_handle: u32,
    #[prost(bytes = "vec", tag = "3")]
    pub pdu: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "4")]
    pub encrypt: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DisconnectCmd {
    #[prost(int32, tag = "1")]
    pub conn_handle: i32,
}
/// *
/// PeripheralModeCmd
///
/// Enable peripheral mode.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PeripheralModeCmd {
    #[prost(bytes = "vec", tag = "1")]
    pub scan_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub scanrsp_data: ::prost::alloc::vec::Vec<u8>,
}
/// *
/// StartCmd
///
/// Enable peripheral advertising and accept connections.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StartCmd {}
/// *
/// StopCmd
///
/// Terminate active connection and stop peripheral.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StopCmd {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HijackMasterCmd {
    #[prost(uint32, tag = "1")]
    pub access_address: u32,
}
/// *
/// HijackSlaveCmd
///
/// Initiate an existing connection hijacking, targeting
/// its slave device.
///
/// `access_address` specifies the target Access Address
///     of the connection to hijack.
///
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HijackSlaveCmd {
    #[prost(uint32, tag = "1")]
    pub access_address: u32,
}
/// *
/// HijackBothCmd
///
/// Initiate an existing connection hijacking, targeting
/// both devices (establish a Man-in-the-Middle in an existing connection).
///
/// `access_address` specifies the target Access Address
///     of the connection to hijack.
///
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HijackBothCmd {
    #[prost(uint32, tag = "1")]
    pub access_address: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetEncryptionCmd {
    #[prost(int32, tag = "1")]
    pub conn_handle: i32,
    #[prost(bool, tag = "2")]
    pub enabled: bool,
    #[prost(bytes = "vec", tag = "3")]
    pub ll_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub ll_iv: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "6")]
    pub rand: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "7")]
    pub ediv: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReactiveJamCmd {
    #[prost(uint32, tag = "1")]
    pub channel: u32,
    #[prost(bytes = "vec", tag = "2")]
    pub pattern: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "3")]
    pub position: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PrepareSequenceCmd {
    #[prost(message, optional, tag = "1")]
    pub trigger: ::core::option::Option<prepare_sequence_cmd::Trigger>,
    #[prost(uint32, tag = "2")]
    pub id: u32,
    #[prost(enumeration = "BleDirection", tag = "3")]
    pub direction: i32,
    #[prost(message, repeated, tag = "4")]
    pub sequence: ::prost::alloc::vec::Vec<prepare_sequence_cmd::PendingPacket>,
}
/// Nested message and enum types in `PrepareSequenceCmd`.
pub mod prepare_sequence_cmd {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct ReceptionTrigger {
        #[prost(bytes = "vec", tag = "1")]
        pub pattern: ::prost::alloc::vec::Vec<u8>,
        #[prost(bytes = "vec", tag = "2")]
        pub mask: ::prost::alloc::vec::Vec<u8>,
        #[prost(uint32, tag = "3")]
        pub offset: u32,
    }
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct ConnectionEventTrigger {
        #[prost(uint32, tag = "1")]
        pub connection_event: u32,
    }
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct ManualTrigger {}
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Trigger {
        #[prost(oneof = "trigger::Trigger", tags = "1, 2, 3")]
        pub trigger: ::core::option::Option<trigger::Trigger>,
    }
    /// Nested message and enum types in `Trigger`.
    pub mod trigger {
        #[derive(Clone, PartialEq, ::prost::Oneof)]
        pub enum Trigger {
            #[prost(message, tag = "1")]
            Reception(super::ReceptionTrigger),
            #[prost(message, tag = "2")]
            ConnectionEvent(super::ConnectionEventTrigger),
            #[prost(message, tag = "3")]
            Manual(super::ManualTrigger),
        }
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct PendingPacket {
        #[prost(bytes = "vec", tag = "1")]
        pub packet: ::prost::alloc::vec::Vec<u8>,
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TriggerSequenceCmd {
    #[prost(uint32, tag = "1")]
    pub id: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeleteSequenceCmd {
    #[prost(uint32, tag = "1")]
    pub id: u32,
}
/// ******************************************
/// ******************************************
/// Ble Notification messages
/// ******************************************
/// *****************************************
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Triggered {
    #[prost(uint32, tag = "1")]
    pub id: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AccessAddressDiscovered {
    #[prost(uint32, tag = "1")]
    pub access_address: u32,
    #[prost(int32, optional, tag = "2")]
    pub rssi: ::core::option::Option<i32>,
    #[prost(uint64, optional, tag = "3")]
    pub timestamp: ::core::option::Option<u64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AdvPduReceived {
    #[prost(enumeration = "BleAdvType", tag = "1")]
    pub adv_type: i32,
    #[prost(int32, tag = "2")]
    pub rssi: i32,
    #[prost(bytes = "vec", tag = "3")]
    pub bd_address: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub adv_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "BleAddrType", tag = "5")]
    pub addr_type: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Connected {
    #[prost(bytes = "vec", tag = "1")]
    pub initiator: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub advertiser: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "3")]
    pub access_address: u32,
    ///
    /// uint32 crc_init = 4;
    /// uint32 hop_interval = 5;
    /// uint32 hop_increment = 6;
    /// bytes channel_map = 7;
    #[prost(uint32, tag = "8")]
    pub conn_handle: u32,
    #[prost(enumeration = "BleAddrType", tag = "9")]
    pub adv_addr_type: i32,
    #[prost(enumeration = "BleAddrType", tag = "10")]
    pub init_addr_type: i32,
}
/// *
/// Disconnected
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Disconnected {
    #[prost(uint32, tag = "1")]
    pub reason: u32,
    #[prost(uint32, tag = "2")]
    pub conn_handle: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Synchronized {
    #[prost(uint32, tag = "1")]
    pub access_address: u32,
    #[prost(uint32, tag = "2")]
    pub crc_init: u32,
    #[prost(uint32, tag = "3")]
    pub hop_interval: u32,
    #[prost(uint32, tag = "4")]
    pub hop_increment: u32,
    #[prost(bytes = "vec", tag = "5")]
    pub channel_map: ::prost::alloc::vec::Vec<u8>,
}
/// *
/// Desynchronized
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Desynchronized {
    #[prost(uint32, tag = "1")]
    pub access_address: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Hijacked {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(uint32, tag = "2")]
    pub access_address: u32,
}
/// *
/// Injected
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Injected {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(uint32, tag = "2")]
    pub access_address: u32,
    #[prost(uint32, tag = "3")]
    pub injection_attempts: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RawPduReceived {
    #[prost(enumeration = "BleDirection", tag = "1")]
    pub direction: i32,
    #[prost(uint32, tag = "2")]
    pub channel: u32,
    #[prost(int32, optional, tag = "3")]
    pub rssi: ::core::option::Option<i32>,
    #[prost(uint64, optional, tag = "4")]
    pub timestamp: ::core::option::Option<u64>,
    #[prost(uint64, optional, tag = "5")]
    pub relative_timestamp: ::core::option::Option<u64>,
    #[prost(bool, optional, tag = "6")]
    pub crc_validity: ::core::option::Option<bool>,
    #[prost(uint32, tag = "7")]
    pub access_address: u32,
    #[prost(bytes = "vec", tag = "8")]
    pub pdu: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "9")]
    pub crc: u32,
    #[prost(uint32, tag = "10")]
    pub conn_handle: u32,
    #[prost(bool, tag = "11")]
    pub processed: bool,
    #[prost(bool, tag = "12")]
    pub decrypted: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PduReceived {
    #[prost(enumeration = "BleDirection", tag = "1")]
    pub direction: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub pdu: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "3")]
    pub conn_handle: u32,
    #[prost(bool, tag = "4")]
    pub processed: bool,
    #[prost(bool, tag = "5")]
    pub decrypted: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    #[prost(
        oneof = "message::Msg",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 33, 34, 35, 36, 38, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 37"
    )]
    pub msg: ::core::option::Option<message::Msg>,
}
/// Nested message and enum types in `Message`.
pub mod message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Msg {
        /// Messages
        #[prost(message, tag = "1")]
        SetBdAddr(super::SetBdAddressCmd),
        #[prost(message, tag = "2")]
        SniffAdv(super::SniffAdvCmd),
        #[prost(message, tag = "3")]
        JamAdv(super::JamAdvCmd),
        #[prost(message, tag = "4")]
        JamAdvChan(super::JamAdvOnChannelCmd),
        #[prost(message, tag = "5")]
        SniffConnreq(super::SniffConnReqCmd),
        #[prost(message, tag = "6")]
        SniffAa(super::SniffAccessAddressCmd),
        #[prost(message, tag = "7")]
        SniffConn(super::SniffActiveConnCmd),
        #[prost(message, tag = "8")]
        JamConn(super::JamConnCmd),
        #[prost(message, tag = "9")]
        ScanMode(super::ScanModeCmd),
        #[prost(message, tag = "10")]
        AdvMode(super::AdvModeCmd),
        #[prost(message, tag = "11")]
        SetAdvData(super::SetAdvDataCmd),
        #[prost(message, tag = "12")]
        CentralMode(super::CentralModeCmd),
        #[prost(message, tag = "13")]
        Connect(super::ConnectToCmd),
        #[prost(message, tag = "14")]
        SendRawPdu(super::SendRawPduCmd),
        #[prost(message, tag = "15")]
        SendPdu(super::SendPduCmd),
        #[prost(message, tag = "16")]
        Disconnect(super::DisconnectCmd),
        #[prost(message, tag = "17")]
        PeriphMode(super::PeripheralModeCmd),
        #[prost(message, tag = "18")]
        Start(super::StartCmd),
        #[prost(message, tag = "19")]
        Stop(super::StopCmd),
        #[prost(message, tag = "20")]
        HijackMaster(super::HijackMasterCmd),
        #[prost(message, tag = "21")]
        HijackSlave(super::HijackSlaveCmd),
        #[prost(message, tag = "22")]
        HijackBoth(super::HijackBothCmd),
        #[prost(message, tag = "33")]
        Encryption(super::SetEncryptionCmd),
        #[prost(message, tag = "34")]
        ReactiveJam(super::ReactiveJamCmd),
        #[prost(message, tag = "35")]
        Prepare(super::PrepareSequenceCmd),
        #[prost(message, tag = "36")]
        Trigger(super::TriggerSequenceCmd),
        #[prost(message, tag = "38")]
        DeleteSeq(super::DeleteSequenceCmd),
        /// Notifications
        #[prost(message, tag = "23")]
        AaDisc(super::AccessAddressDiscovered),
        #[prost(message, tag = "24")]
        AdvPdu(super::AdvPduReceived),
        #[prost(message, tag = "25")]
        Connected(super::Connected),
        #[prost(message, tag = "26")]
        Disconnected(super::Disconnected),
        #[prost(message, tag = "27")]
        Synchronized(super::Synchronized),
        #[prost(message, tag = "28")]
        Hijacked(super::Hijacked),
        #[prost(message, tag = "29")]
        Pdu(super::PduReceived),
        #[prost(message, tag = "30")]
        RawPdu(super::RawPduReceived),
        #[prost(message, tag = "31")]
        Injected(super::Injected),
        #[prost(message, tag = "32")]
        Desynchronized(super::Desynchronized),
        #[prost(message, tag = "37")]
        Triggered(super::Triggered),
    }
}
/// *
/// Low-level commands
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BleCommand {
    /// Set BD address.
    SetBdAddress = 0,
    /// Sniff advertisements.
    SniffAdv = 1,
    /// Jam advertisements.
    JamAdv = 2,
    /// Jam advertisements on a single channel.
    JamAdvOnChannel = 3,
    /// Jam a specific pattern on a single channel.
    ReactiveJam = 4,
    /// Sniff CONN_REQ PDUs and sync with connection.
    SniffConnReq = 5,
    /// Sniff active connection.
    SniffAccessAddress = 6,
    SniffActiveConn = 7,
    /// Connection jamming.
    JamConn = 8,
    /// Scanner mode.
    ScanMode = 9,
    /// Advertiser mode.
    AdvMode = 10,
    /// SetAdvData shared with Peripheral mode.
    SetAdvData = 11,
    /// Central mode.
    CentralMode = 12,
    ConnectTo = 13,
    SendRawPdu = 14,
    SendPdu = 15,
    Disconnect = 16,
    /// Peripheral mode.
    PeripheralMode = 17,
    /// Common to multiple modes.
    Start = 18,
    Stop = 19,
    SetEncryption = 20,
    /// Hijack mode.
    HijackMaster = 21,
    HijackSlave = 22,
    HijackBoth = 23,
    /// Sequence mode
    PrepareSequence = 24,
    TriggerSequence = 25,
    DeleteSequence = 26,
}
impl BleCommand {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::SetBdAddress => "SetBdAddress",
            Self::SniffAdv => "SniffAdv",
            Self::JamAdv => "JamAdv",
            Self::JamAdvOnChannel => "JamAdvOnChannel",
            Self::ReactiveJam => "ReactiveJam",
            Self::SniffConnReq => "SniffConnReq",
            Self::SniffAccessAddress => "SniffAccessAddress",
            Self::SniffActiveConn => "SniffActiveConn",
            Self::JamConn => "JamConn",
            Self::ScanMode => "ScanMode",
            Self::AdvMode => "AdvMode",
            Self::SetAdvData => "SetAdvData",
            Self::CentralMode => "CentralMode",
            Self::ConnectTo => "ConnectTo",
            Self::SendRawPdu => "SendRawPDU",
            Self::SendPdu => "SendPDU",
            Self::Disconnect => "Disconnect",
            Self::PeripheralMode => "PeripheralMode",
            Self::Start => "Start",
            Self::Stop => "Stop",
            Self::SetEncryption => "SetEncryption",
            Self::HijackMaster => "HijackMaster",
            Self::HijackSlave => "HijackSlave",
            Self::HijackBoth => "HijackBoth",
            Self::PrepareSequence => "PrepareSequence",
            Self::TriggerSequence => "TriggerSequence",
            Self::DeleteSequence => "DeleteSequence",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SetBdAddress" => Some(Self::SetBdAddress),
            "SniffAdv" => Some(Self::SniffAdv),
            "JamAdv" => Some(Self::JamAdv),
            "JamAdvOnChannel" => Some(Self::JamAdvOnChannel),
            "ReactiveJam" => Some(Self::ReactiveJam),
            "SniffConnReq" => Some(Self::SniffConnReq),
            "SniffAccessAddress" => Some(Self::SniffAccessAddress),
            "SniffActiveConn" => Some(Self::SniffActiveConn),
            "JamConn" => Some(Self::JamConn),
            "ScanMode" => Some(Self::ScanMode),
            "AdvMode" => Some(Self::AdvMode),
            "SetAdvData" => Some(Self::SetAdvData),
            "CentralMode" => Some(Self::CentralMode),
            "ConnectTo" => Some(Self::ConnectTo),
            "SendRawPDU" => Some(Self::SendRawPdu),
            "SendPDU" => Some(Self::SendPdu),
            "Disconnect" => Some(Self::Disconnect),
            "PeripheralMode" => Some(Self::PeripheralMode),
            "Start" => Some(Self::Start),
            "Stop" => Some(Self::Stop),
            "SetEncryption" => Some(Self::SetEncryption),
            "HijackMaster" => Some(Self::HijackMaster),
            "HijackSlave" => Some(Self::HijackSlave),
            "HijackBoth" => Some(Self::HijackBoth),
            "PrepareSequence" => Some(Self::PrepareSequence),
            "TriggerSequence" => Some(Self::TriggerSequence),
            "DeleteSequence" => Some(Self::DeleteSequence),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BleAdvType {
    AdvUnknown = 0,
    AdvInd = 1,
    AdvDirectInd = 2,
    AdvNonconnInd = 3,
    AdvScanInd = 4,
    AdvScanRsp = 5,
}
impl BleAdvType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::AdvUnknown => "ADV_UNKNOWN",
            Self::AdvInd => "ADV_IND",
            Self::AdvDirectInd => "ADV_DIRECT_IND",
            Self::AdvNonconnInd => "ADV_NONCONN_IND",
            Self::AdvScanInd => "ADV_SCAN_IND",
            Self::AdvScanRsp => "ADV_SCAN_RSP",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ADV_UNKNOWN" => Some(Self::AdvUnknown),
            "ADV_IND" => Some(Self::AdvInd),
            "ADV_DIRECT_IND" => Some(Self::AdvDirectInd),
            "ADV_NONCONN_IND" => Some(Self::AdvNonconnInd),
            "ADV_SCAN_IND" => Some(Self::AdvScanInd),
            "ADV_SCAN_RSP" => Some(Self::AdvScanRsp),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BleDirection {
    Unknown = 0,
    MasterToSlave = 1,
    SlaveToMaster = 2,
    InjectionToSlave = 3,
    InjectionToMaster = 4,
}
impl BleDirection {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "UNKNOWN",
            Self::MasterToSlave => "MASTER_TO_SLAVE",
            Self::SlaveToMaster => "SLAVE_TO_MASTER",
            Self::InjectionToSlave => "INJECTION_TO_SLAVE",
            Self::InjectionToMaster => "INJECTION_TO_MASTER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN" => Some(Self::Unknown),
            "MASTER_TO_SLAVE" => Some(Self::MasterToSlave),
            "SLAVE_TO_MASTER" => Some(Self::SlaveToMaster),
            "INJECTION_TO_SLAVE" => Some(Self::InjectionToSlave),
            "INJECTION_TO_MASTER" => Some(Self::InjectionToMaster),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BleAddrType {
    Public = 0,
    Random = 1,
}
impl BleAddrType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Public => "PUBLIC",
            Self::Random => "RANDOM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PUBLIC" => Some(Self::Public),
            "RANDOM" => Some(Self::Random),
            _ => None,
        }
    }
}
