// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeviceResetQuery {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeviceReadyResp {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetTransportSpeed {
    #[prost(uint32, tag = "1")]
    pub speed: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceInfoResp {
    /// Device type.
    #[prost(uint32, tag = "1")]
    pub r#type: u32,
    /// Device ID
    #[prost(bytes = "vec", tag = "2")]
    pub devid: ::prost::alloc::vec::Vec<u8>,
    /// Supported minimal protocol version.
    #[prost(uint32, tag = "3")]
    pub proto_min_ver: u32,
    /// Maximum supported speed (if useful).
    #[prost(uint32, tag = "4")]
    pub max_speed: u32,
    /// Device firmware info.
    #[prost(bytes = "vec", tag = "5")]
    pub fw_author: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "6")]
    pub fw_url: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "7")]
    pub fw_version_major: u32,
    #[prost(uint32, tag = "8")]
    pub fw_version_minor: u32,
    #[prost(uint32, tag = "9")]
    pub fw_version_rev: u32,
    #[prost(uint32, repeated, tag = "10")]
    pub capabilities: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeviceDomainInfoResp {
    #[prost(uint32, tag = "1")]
    pub domain: u32,
    #[prost(uint64, tag = "2")]
    pub supported_commands: u64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeviceInfoQuery {
    #[prost(uint32, tag = "1")]
    pub proto_ver: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DeviceDomainInfoQuery {
    #[prost(uint32, tag = "1")]
    pub domain: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    #[prost(oneof = "message::Msg", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub msg: ::core::option::Option<message::Msg>,
}
/// Nested message and enum types in `Message`.
pub mod message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Msg {
        #[prost(message, tag = "1")]
        ResetQuery(super::DeviceResetQuery),
        #[prost(message, tag = "2")]
        ReadyResp(super::DeviceReadyResp),
        #[prost(message, tag = "3")]
        InfoQuery(super::DeviceInfoQuery),
        #[prost(message, tag = "4")]
        InfoResp(super::DeviceInfoResp),
        #[prost(message, tag = "5")]
        DomainQuery(super::DeviceDomainInfoQuery),
        #[prost(message, tag = "6")]
        DomainResp(super::DeviceDomainInfoResp),
        #[prost(message, tag = "7")]
        SetSpeed(super::SetTransportSpeed),
    }
}
/// Domains definition.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Domain {
    None = 0,
    Phy = 16777216,
    BtClassic = 33554432,
    BtLe = 50331648,
    Dot15d4 = 67108864,
    SixLowPan = 83886080,
    Esb = 100663296,
    LogitechUnifying = 117440512,
    Mosart = 134217728,
    Ant = 150994944,
    AntPlus = 167772160,
    AntFs = 184549376,
}
impl Domain {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::None => "_DomainNone",
            Self::Phy => "Phy",
            Self::BtClassic => "BtClassic",
            Self::BtLe => "BtLE",
            Self::Dot15d4 => "Dot15d4",
            Self::SixLowPan => "SixLowPan",
            Self::Esb => "Esb",
            Self::LogitechUnifying => "LogitechUnifying",
            Self::Mosart => "Mosart",
            Self::Ant => "ANT",
            Self::AntPlus => "ANT_Plus",
            Self::AntFs => "ANT_FS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "_DomainNone" => Some(Self::None),
            "Phy" => Some(Self::Phy),
            "BtClassic" => Some(Self::BtClassic),
            "BtLE" => Some(Self::BtLe),
            "Dot15d4" => Some(Self::Dot15d4),
            "SixLowPan" => Some(Self::SixLowPan),
            "Esb" => Some(Self::Esb),
            "LogitechUnifying" => Some(Self::LogitechUnifying),
            "Mosart" => Some(Self::Mosart),
            "ANT" => Some(Self::Ant),
            "ANT_Plus" => Some(Self::AntPlus),
            "ANT_FS" => Some(Self::AntFs),
            _ => None,
        }
    }
}
/// *
/// DeviceType specifies the supported devices.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DeviceType {
    Esp32BleFuzzer = 0,
    Butterfly = 1,
    BtleJack = 2,
    VirtualDevice = 4,
}
impl DeviceType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Esp32BleFuzzer => "Esp32BleFuzzer",
            Self::Butterfly => "Butterfly",
            Self::BtleJack => "BtleJack",
            Self::VirtualDevice => "VirtualDevice",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Esp32BleFuzzer" => Some(Self::Esp32BleFuzzer),
            "Butterfly" => Some(Self::Butterfly),
            "BtleJack" => Some(Self::BtleJack),
            "VirtualDevice" => Some(Self::VirtualDevice),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Capability {
    CapNone = 0,
    Scan = 1,
    Sniff = 2,
    Inject = 4,
    Jam = 8,
    Hijack = 16,
    Hook = 32,
    SimulateRole = 64,
    NoRawData = 128,
}
impl Capability {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::CapNone => "_CapNone",
            Self::Scan => "Scan",
            Self::Sniff => "Sniff",
            Self::Inject => "Inject",
            Self::Jam => "Jam",
            Self::Hijack => "Hijack",
            Self::Hook => "Hook",
            Self::SimulateRole => "SimulateRole",
            Self::NoRawData => "NoRawData",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "_CapNone" => Some(Self::CapNone),
            "Scan" => Some(Self::Scan),
            "Sniff" => Some(Self::Sniff),
            "Inject" => Some(Self::Inject),
            "Jam" => Some(Self::Jam),
            "Hijack" => Some(Self::Hijack),
            "Hook" => Some(Self::Hook),
            "SimulateRole" => Some(Self::SimulateRole),
            "NoRawData" => Some(Self::NoRawData),
            _ => None,
        }
    }
}
