// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CmdResult {
    #[prost(enumeration = "ResultCode", tag = "1")]
    pub result: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Progress {
    #[prost(uint32, tag = "1")]
    pub value: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DebugMsg {
    #[prost(uint32, tag = "1")]
    pub level: u32,
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VerboseMsg {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    #[prost(oneof = "message::Msg", tags = "1, 2, 3, 4, 5")]
    pub msg: ::core::option::Option<message::Msg>,
}
/// Nested message and enum types in `Message`.
pub mod message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Msg {
        #[prost(enumeration = "super::ResultCode", tag = "1")]
        Result(i32),
        #[prost(message, tag = "2")]
        CmdResult(super::CmdResult),
        #[prost(message, tag = "3")]
        Progress(super::Progress),
        #[prost(message, tag = "4")]
        Debug(super::DebugMsg),
        #[prost(message, tag = "5")]
        Verbose(super::VerboseMsg),
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ResultCode {
    Success = 0,
    Error = 1,
    ParameterError = 2,
    Disconnected = 3,
    WrongMode = 4,
    UnsupportedDomain = 5,
    Busy = 6,
}
impl ResultCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Success => "SUCCESS",
            Self::Error => "ERROR",
            Self::ParameterError => "PARAMETER_ERROR",
            Self::Disconnected => "DISCONNECTED",
            Self::WrongMode => "WRONG_MODE",
            Self::UnsupportedDomain => "UNSUPPORTED_DOMAIN",
            Self::Busy => "BUSY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SUCCESS" => Some(Self::Success),
            "ERROR" => Some(Self::Error),
            "PARAMETER_ERROR" => Some(Self::ParameterError),
            "DISCONNECTED" => Some(Self::Disconnected),
            "WRONG_MODE" => Some(Self::WrongMode),
            "UNSUPPORTED_DOMAIN" => Some(Self::UnsupportedDomain),
            "BUSY" => Some(Self::Busy),
            _ => None,
        }
    }
}
